"""
Django settings for loanpro project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k!x+^6b#7^_=@^r*k22fbar^+0^%ew#d(66r7m79!m=xxrjbk0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "apploan",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #"django.middleware.locale.LocaleMiddleware",
]

ROOT_URLCONF = 'loanpro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apploan.context_processors.menu_setting',
                'apploan.context_processors.loan_rates',
                'apploan.views.footerSettings',
            ],
        },
    },
]

WSGI_APPLICATION = 'loanpro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#DATABASES = {
    #'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': BASE_DIR / 'db.sqlite3',
    #}
#}

#from decouple import config

#DATABASES = {
    #'default': {
        #'ENGINE': 'django.db.backends.postgresql',
        #'NAME': config('DB_NAME'),
        #'USER': config('DB_USER'),
        #'PASSWORD': config('DB_PASSWORD'),
        #'HOST': config('DB_HOST', default='localhost'),
        #'PORT': config('DB_PORT', default='5432'),
    #}
#}

from decouple import config
import os

ENV = os.getenv('DJANGO_ENV', 'DEVELOPMENT')

if ENV.upper() == 'PRODUCTION':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

#DATABASES = {
    #'default': {
        #'ENGINE': 'django.db.backends.postgresql',
        #'NAME': 'sgvloans',
        #'USER': 'postgres',
        #'PASSWORD': '12345',
        #'HOST': 'localhost',
        #'PORT': '5432',
    #}
#}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

USE_I18N = True

LANGUAGES = (
    ("en", _("English")),
    ("zh-hans", _("Chinese")), 
    ("ms", _("Malay")),
)

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

UNFOLD = {
    "SHOW_LANGUAGES": True,
}

TIME_ZONE = 'Asia/Singapore'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "apploan" / "static",
]


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SHOW_LANGUAGES": True,
    "SITE_TITLE": "SGVehicleLoans Admin",
    "SITE_HEADER": "SGVehicleLoans Admin",
    "DASHBOARD_CALLBACK": "apploan.views.dashboard_callback",

    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/png",
            "href": lambda request: static("apploan/images/sgvlogo.png"), 
        },
    ],
    
    "SIDEBAR": {
        "show_search": True,  # Search in applications and models names
        "command_search": False,  # Replace the sidebar search with the command search
        "show_all_applications": True,  # Dropdown with all applications and models
        "navigation": [
            {
                "title": _("Main"),
                "separator": True,  # Top border
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:index"),
                        #"badge": "Admin",
                        #"permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
            {
                "title": _("Records"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": _("General Loan Application"),
                        "icon": "data_table",
                        "link": reverse_lazy("admin:apploan_application_changelist"), #admin:<app_label>_<model_name>_changelist
                    },
                    {
                        "title": _("Application COE Renewal Car"),
                        "icon": "autorenew",
                        "link": reverse_lazy("admin:apploan_carcoe_changelist"), 
                    },
                    {
                        "title": _("Application COE Renewal Motorcycle"),
                        "icon": "cached",
                        "link": reverse_lazy("admin:apploan_motorcoe_changelist"), 
                    },
                    {
                        "title": _("General Loan Enquiries"),
                        "icon": "tooltip_2",
                        "link": reverse_lazy("admin:apploan_generalenquiry_changelist"),
                    },
                    {
                        "title": _("Enquiry COE Renew Car"),
                        "icon": "autorenew",
                        "link": reverse_lazy("admin:apploan_carenquiry_changelist"),
                    },
                    {
                        "title": _("Enquiry COE Renew Motorcycle"),
                        "icon": "cached",
                        "link": reverse_lazy("admin:apploan_motorcycleenquiry_changelist"),
                    },
                    {
                        "title": _("Car Installment Submission"),
                        "icon": "chat_paste_go",
                        "link": reverse_lazy("admin:apploan_installmentsubmit_changelist"),
                    },
                    {
                        "title": _("Contact Enquiry"),
                        "icon": "contact_phone",
                        "link": reverse_lazy("admin:apploan_contact_changelist"),
                    },
                ],
            },
            {
                "title": _("Quotations"),
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Qoute Car"),
                        "icon": "request_quote",
                        "link": reverse_lazy("admin:apploan_quotecar_changelist"),
                    },
                    {
                        "title": _("Qoute Motorcycle"),
                        "icon": "draft",
                        "link": reverse_lazy("admin:apploan_quotemotor_changelist"),
                    },
                ],
            },
            {
                "title": _("CMS"),
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Menu"),
                        "icon": "menu",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:apploan_menusetting_changelist"),
                        #"badge": "Admin",
                        #"permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Loan Rate"),
                        "icon": "rate_review",
                        "link": reverse_lazy("admin:apploan_loanrate_changelist"), 
                    },
                    {
                        "title": _("Header Videos"),
                        "icon": "video_camera_back_add",
                        "link": reverse_lazy("admin:apploan_headervideo_changelist"), 
                    },
                    {
                        "title": _("Header Images"),
                        "icon": "add_photo_alternate",
                        "link": reverse_lazy("admin:apploan_headerimage_changelist"), 
                    },
                    {
                        "title": _("Footer"),
                        "icon": "edit_location_alt",
                        "link": reverse_lazy("admin:apploan_footersetting_changelist"), 
                    },

                ],
            },
            {
                "title": _("Authentication"),
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "passkey",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                        "badge": "Superuser",
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        #"badge": "Superuser",
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
        ],
    },
}

def environment_callback(request):
    """
    Callback has to return a list of two values represeting text value and the color
    type of the label displayed in top right corner.
    """
    return ["Production", "danger"] # info, danger, warning, success