# Generated by Django 4.2 on 2025-12-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_home', models.BooleanField(default=True)),
                ('show_financing', models.BooleanField(default=True)),
                ('show_coe', models.BooleanField(default=True)),
                ('show_insurance', models.BooleanField(default=True)),
                ('show_offers', models.BooleanField(default=True)),
                ('show_resources', models.BooleanField(default=True)),
                ('show_about', models.BooleanField(default=True)),
                ('show_contact', models.BooleanField(default=True)),
                ('finance_used', models.BooleanField(default=True)),
                ('finance_new', models.BooleanField(default=True)),
                ('finance_direct', models.BooleanField(default=True)),
                ('finance_coe_car', models.BooleanField(default=True)),
                ('finance_refinance', models.BooleanField(default=True)),
                ('finance_inhouse', models.BooleanField(default=True)),
                ('finance_phv', models.BooleanField(default=True)),
                ('coe_car', models.BooleanField(default=True)),
                ('coe_moto', models.BooleanField(default=True)),
                ('insurance_car', models.BooleanField(default=True)),
                ('insurance_motor', models.BooleanField(default=True)),
            ],
        ),
    ]
