# Generated by Django 4.2 on 2026-01-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('car_source', models.CharField(choices=[('direct_owner', 'Direct Owner'), ('car_dealer', 'Car Dealer')], max_length=50)),
                ('vehicle_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('omv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registration_date', models.DateField()),
                ('registration_number', models.CharField(max_length=50)),
                ('lta_access_code', models.CharField(max_length=50)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_tenure', models.PositiveIntegerField()),
                ('loan_type', models.CharField(choices=[('used_car', 'Used Car Loan'), ('new_car', 'New Car Loan'), ('coe_car', 'COE Car Loan'), ('direct_buyer', 'Direct Buyer → Seller Loan')], max_length=50)),
                ('repayment_mode', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('preferred_bank', models.CharField(choices=[('maybank', 'Maybank'), ('uob', 'UOB'), ('dbs', 'DBS/POSB'), ('ocbc', 'OCBC'), ('hlf', 'Hong Leong Finance'), ('others', 'Others')], max_length=50)),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remarks', models.TextField()),
                ('privacy_policy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyCOE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motor', 'Motorcycle')], max_length=10)),
                ('full_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('consent', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('privacy_policy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryRenew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('loan_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle')], max_length=20)),
                ('coe_category_type', models.CharField(blank=True, choices=[('Category A', 'Category A (Cars up To 1,600cc)'), ('Category B', 'Category B (Cars Above 1,600cc)'), ('Category C', 'Category C (Goods Vehicles & Buses)')], max_length=50, null=True)),
                ('is_phv', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('coe_renewal_period', models.CharField(choices=[('5-Year Renewal', '5-Year Renewal'), ('10-Year Renewal', '10-Year Renewal')], max_length=20)),
                ('privacy_policy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('used_cm', 'Used Car & Motorcycle'), ('new_cm', 'New Car & Motorcycle'), ('direct_bs', 'Direct Buyer - Seller'), ('coe_car', 'COE Car')], max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='header_images/')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(choices=[('car', 'Car Insurance'), ('motorcycle', 'Motorcycle Insurance')], max_length=20, unique=True)),
                ('video', models.FileField(upload_to='header_videos/')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=50)),
                ('loan_display', models.CharField(blank=True, max_length=100, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('financing', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_home', models.BooleanField(default=True, verbose_name='Show Home')),
                ('show_financing', models.BooleanField(default=True, verbose_name='Show Financing')),
                ('show_coe', models.BooleanField(default=True, verbose_name='Show COE')),
                ('show_insurance', models.BooleanField(default=True, verbose_name='Show Insurance')),
                ('show_rates', models.BooleanField(default=True, verbose_name='Show Rates')),
                ('show_guides', models.BooleanField(default=True, verbose_name='Show Guides')),
                ('show_about', models.BooleanField(default=True, verbose_name='Show About')),
                ('show_contact', models.BooleanField(default=True, verbose_name='Show Contact')),
                ('finance_used', models.BooleanField(default=True, verbose_name='Used Cars')),
                ('finance_new', models.BooleanField(default=True, verbose_name='New Cars')),
                ('finance_direct', models.BooleanField(default=True, verbose_name='Direct Financing')),
                ('finance_coe_car', models.BooleanField(default=True, verbose_name='COE Cars')),
                ('finance_refinance', models.BooleanField(default=True, verbose_name='Refinance')),
                ('finance_inhouse', models.BooleanField(default=True, verbose_name='In-House Financing')),
                ('finance_phv', models.BooleanField(default=True, verbose_name='PHV Financing')),
                ('coe_car', models.BooleanField(default=True, verbose_name='Car COE')),
                ('coe_moto', models.BooleanField(default=True, verbose_name='Motorcycle COE')),
                ('insurance_car', models.BooleanField(default=True, verbose_name='Car Insurance')),
                ('insurance_motor', models.BooleanField(default=True, verbose_name='Motorcycle Insurance')),
                ('guides_calc', models.BooleanField(default=True, verbose_name='Calculator')),
                ('guides_faq', models.BooleanField(default=True, verbose_name='FAQ')),
                ('guides_install', models.BooleanField(default=True, verbose_name='Installment')),
                ('guides_pay', models.BooleanField(default=True, verbose_name='Payment')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Honda', 'Honda'), ('BMW', 'BMW'), ('Toyota', 'Toyota'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Audi', 'Audi'), ('Volkswagen', 'Volkswagen'), ('Nissan', 'Nissan'), ('Mazda', 'Mazda'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Subaru', 'Subaru'), ('Volvo', 'Volvo'), ('Mitsubishi', 'Mitsubishi'), ('Ford', 'Ford'), ('Lexus', 'Lexus'), ('Porsche', 'Porsche'), ('Jaguar', 'Jaguar'), ('Land Rover', 'Land Rover'), ('Chevrolet', 'Chevrolet'), ('Peugeot', 'Peugeot'), ('Renault', 'Renault'), ('Ferrari', 'Ferrari'), ('Lamborghini', 'Lamborghini'), ('Maserati', 'Maserati'), ('Bentley', 'Bentley'), ('Rolls-Royce', 'Rolls-Royce'), ('McLaren', 'McLaren'), ('Bugatti', 'Bugatti'), ('Tesla', 'Tesla'), ('Infiniti', 'Infiniti'), ('Acura', 'Acura'), ('Mini', 'Mini'), ('Suzuki', 'Suzuki'), ('Isuzu', 'Isuzu'), ('Citroen', 'Citroen'), ('Alfa Romeo', 'Alfa Romeo'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Chrysler', 'Chrysler'), ('Daihatsu', 'Daihatsu')], max_length=100)),
                ('model', models.CharField(max_length=255)),
                ('year_reg', models.CharField(max_length=20)),
                ('scheme', models.CharField(choices=[('Off-peak', 'Off-peak'), ('Non off-peak', 'Non off-peak')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorce', 'Divorce')], max_length=10)),
                ('number', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('occupation', models.CharField(choices=[('Manager', 'Manager'), ('Engineer', 'Engineer'), ('Driver', 'Driver'), ('Technician', 'Technician'), ('Teacher', 'Teacher'), ('Nurse', 'Nurse'), ('Doctor', 'Doctor'), ('Accountant', 'Accountant'), ('Administrator', 'Administrator'), ('Salesperson', 'Salesperson'), ('Customer Service', 'Customer Service'), ('Supervisor', 'Supervisor'), ('Chef', 'Chef'), ('Cashier', 'Cashier'), ('Security Officer', 'Security Officer'), ('Cleaner', 'Cleaner'), ('Construction Worker', 'Construction Worker'), ('IT Specialist', 'IT Specialist'), ('Software Developer', 'Software Developer'), ('Designer', 'Designer'), ('Marketing Executive', 'Marketing Executive'), ('Human Resource', 'Human Resource'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Mechanic', 'Mechanic'), ('Logistics Coordinator', 'Logistics Coordinator'), ('Warehouse Assistant', 'Warehouse Assistant'), ('Delivery Rider', 'Delivery Rider'), ('Waiter', 'Waiter'), ('Barista', 'Barista'), ('Business Owner', 'Business Owner'), ('Self-Employed', 'Self-Employed'), ('Unemployed', 'Unemployed'), ('Student', 'Student'), ('Housewife', 'Housewife'), ('Retiree', 'Retiree'), ('Others', 'Others')], max_length=100)),
                ('vec_number', models.CharField(max_length=50)),
                ('ncd_disc', models.CharField(choices=[('0%', '0%'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%')], max_length=10)),
                ('licence', models.CharField(choices=[('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('5+ Years', '5+ Years')], max_length=50)),
                ('driver', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('claims', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4+', '4+')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('privacy_policy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Yamaha', 'Yamaha'), ('Honda', 'Honda'), ('Suzuki', 'Suzuki'), ('Kawasaki', 'Kawasaki'), ('KTM', 'KTM'), ('Ducati', 'Ducati'), ('Royal Enfield', 'Royal Enfield'), ('BMW', 'BMW Motorrad'), ('Triumph', 'Triumph'), ('CFMOTO', 'CFMOTO'), ('SYM', 'SYM'), ('Kymco', 'Kymco'), ('Aprilia', 'Aprilia'), ('Benelli', 'Benelli'), ('Moto Guzzi', 'Moto Guzzi'), ('Bimota', 'Bimota'), ('Husqvarna', 'Husqvarna'), ('GasGas', 'GasGas'), ('Indian', 'Indian Motorcycle'), ('Harley-Davidson', 'Harley-Davidson'), ('Zero', 'Zero Motorcycles')], max_length=100)),
                ('model', models.CharField(max_length=255)),
                ('year_reg', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorce', 'Divorce')], max_length=10)),
                ('number', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('occupation', models.CharField(choices=[('Manager', 'Manager'), ('Engineer', 'Engineer'), ('Driver', 'Driver'), ('Technician', 'Technician'), ('Teacher', 'Teacher'), ('Nurse', 'Nurse'), ('Doctor', 'Doctor'), ('Accountant', 'Accountant'), ('Administrator', 'Administrator'), ('Salesperson', 'Salesperson'), ('Customer Service', 'Customer Service'), ('Supervisor', 'Supervisor'), ('Chef', 'Chef'), ('Cashier', 'Cashier'), ('Security Officer', 'Security Officer'), ('Cleaner', 'Cleaner'), ('Construction Worker', 'Construction Worker'), ('IT Specialist', 'IT Specialist'), ('Software Developer', 'Software Developer'), ('Designer', 'Designer'), ('Marketing Executive', 'Marketing Executive'), ('Human Resource', 'Human Resource'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Mechanic', 'Mechanic'), ('Logistics Coordinator', 'Logistics Coordinator'), ('Warehouse Assistant', 'Warehouse Assistant'), ('Delivery Rider', 'Delivery Rider'), ('Waiter', 'Waiter'), ('Barista', 'Barista'), ('Business Owner', 'Business Owner'), ('Self-Employed', 'Self-Employed'), ('Unemployed', 'Unemployed'), ('Student', 'Student'), ('Housewife', 'Housewife'), ('Retiree', 'Retiree'), ('Others', 'Others')], max_length=100)),
                ('ride_exp', models.CharField(choices=[('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('5+ Years', '5+ Years')], max_length=50)),
                ('ncd_disc', models.CharField(choices=[('0%', '0%'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%')], max_length=10)),
                ('licence', models.CharField(choices=[('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('5+ Years', '5+ Years')], max_length=50)),
                ('named_rider', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=10)),
                ('claims', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4+', '4+')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('privacy_policy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
            ],
            options={
                'verbose_name': 'General Applications',
                'verbose_name_plural': 'General Applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apploan.apply',),
        ),
        migrations.CreateModel(
            name='CarCOE',
            fields=[
            ],
            options={
                'verbose_name': 'Application COE Renewal Car',
                'verbose_name_plural': 'Application COE Renewal Car',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apploan.applycoe',),
        ),
        migrations.CreateModel(
            name='CarEnquiry',
            fields=[
            ],
            options={
                'verbose_name': 'Enquiry COE Renew Car',
                'verbose_name_plural': 'Enquiries COE Renew Car',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apploan.enquiryrenew',),
        ),
        migrations.CreateModel(
            name='GenEnquiry',
            fields=[
            ],
            options={
                'verbose_name': 'General Enquiries',
                'verbose_name_plural': 'General Enquiries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apploan.enquiry',),
        ),
        migrations.CreateModel(
            name='MotorCOE',
            fields=[
            ],
            options={
                'verbose_name': 'Application COE Renewal Motorcycle',
                'verbose_name_plural': 'Application COE Renewal Motorcycle',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apploan.applycoe',),
        ),
        migrations.CreateModel(
            name='MotorcycleEnquiry',
            fields=[
            ],
            options={
                'verbose_name': 'Enquiry COE Renew Motorcycle',
                'verbose_name_plural': 'Enquiries COE Renew Motorcycle',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apploan.enquiryrenew',),
        ),
    ]
