# Generated by Django 4.2 on 2025-12-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(help_text='E.g., used_car, new_car, direct_buyer', max_length=50, unique=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Interest rate in %', max_digits=5, null=True)),
                ('financing', models.DecimalField(blank=True, decimal_places=0, help_text='Maximum financing %', max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
