# Generated by Django 6.0.1 on 2026-01-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerimage',
            name='image',
            field=models.ImageField(help_text='Supported formats: PNG, JPG. Maximum upload size: 20 MB.', upload_to='header_images/'),
        ),
        migrations.AlterField(
            model_name='headervideo',
            name='video',
            field=models.FileField(help_text='Maximum file size: 20 MB. Please Trim or Compress on (https://www.freeconvert.com/video-compressor) before uploading.', upload_to='header_videos/'),
        ),
    ]
