# Generated by Django 4.2 on 2025-12-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0002_loanrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrate',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='loanrate',
            name='loan_display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanrate',
            name='financing',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='loanrate',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='loanrate',
            name='loan_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
