# Generated by Django 6.0.1 on 2026-01-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0002_alter_headerimage_image_alter_headervideo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default='400 Balestier Road,\nBalestier Plaza #02-23,\nSingapore 329802')),
                ('google_map_embed', models.TextField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.750498216391!2d103.8478215758166!3d1.3256235616514813!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da19d8ad2a9e11%3A0x1b8c2cdaf63e0fbb!2sBalestier%20Plaza!5e0!3m2!1sen!2smy!4v1764923928289!5m2!1sen!2smy')),
                ('hotline', models.CharField(default='(+65) 6444 4400', max_length=50)),
                ('office', models.CharField(default='+65 6681 6778', max_length=50)),
                ('fax', models.CharField(default='+65 6256 1229', max_length=50)),
                ('op_hours_weekdays', models.CharField(default='Mon–Fri: 10am–6pm', max_length=100)),
                ('op_hours_sat', models.CharField(default='Sat: 12pm–4pm', max_length=100)),
                ('facebook_url', models.URLField(default='https://www.facebook.com/login')),
                ('instagram_url', models.URLField(default='https://www.instagram.com/accounts/login/')),
                ('whatsapp_url', models.URLField(default='https://api.whatsapp.com/send?phone=6589259233&text=Hi%2C%20SGVehicleLoans')),
                ('tiktok_url', models.URLField(default='https://www.tiktok.com/login')),
            ],
            options={
                'verbose_name': 'Footer Setting',
                'verbose_name_plural': 'Footer Settings',
            },
        ),
    ]
