# Generated by Django 5.2.8 on 2026-01-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0003_footersetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('nric', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('vehicle_reg', models.CharField(max_length=20)),
                ('install_amount', models.DecimalField(decimal_places=2, help_text='Monthly instalment amount', max_digits=10)),
                ('transfer_amount', models.DecimalField(decimal_places=2, help_text='Amount transferred', max_digits=10)),
                ('reference', models.CharField(max_length=100)),
                ('proof_pay', models.FileField(help_text='Upload transfer receipt', upload_to='installments/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('privacy_policy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='footersetting',
            name='facebook_url',
            field=models.URLField(default='https://www.facebook.com/login', help_text='Please put your Facebook page link here.'),
        ),
        migrations.AlterField(
            model_name='footersetting',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://www.instagram.com/accounts/login/', help_text='Please put your Instagram profile link here.'),
        ),
        migrations.AlterField(
            model_name='footersetting',
            name='tiktok_url',
            field=models.URLField(blank=True, default='https://www.tiktok.com/login', help_text='Please put your TikTok profile link here.'),
        ),
        migrations.AlterField(
            model_name='footersetting',
            name='whatsapp_url',
            field=models.URLField(blank=True, default='https://api.whatsapp.com/send?phone=6589259233&text=Hi%2C%20SGVehicleLoans', help_text='Please put your WhatsApp link here.'),
        ),
    ]
