# Generated by Django 4.2 on 2025-12-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0004_application_enquiry_alter_loanrate_loan_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminnote',
            name='application',
        ),
        migrations.RemoveField(
            model_name='adminnote',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='document',
            name='application',
        ),
        migrations.DeleteModel(
            name='Enquiry',
        ),
        migrations.RemoveField(
            model_name='application',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.RemoveField(
            model_name='application',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='application',
            name='privacy_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AdminNote',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
