# Generated by Django 5.2.8 on 2026-01-19 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0004_installmentsubmit_alter_footersetting_facebook_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenEnquiry',
        ),
        migrations.CreateModel(
            name='GeneralEnquiry',
            fields=[
            ],
            options={
                'verbose_name': 'General Enquiry',
                'verbose_name_plural': 'General Enquiries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apploan.enquiry',),
        ),
    ]
