# Generated by Django 5.2.8 on 2026-01-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0005_delete_genenquiry_generalenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('enquiry_type', models.CharField(choices=[('Car Loan', 'Car Loan'), ('Motorcycle Loan', 'Motorcycle Loan'), ('Insurance', 'Insurance'), ('Other', 'Other')], max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('privacy_policy', models.BooleanField(default=False)),
                ('captcha', models.CharField(help_text='Simple math captcha', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
