# Generated by Django 5.2.8 on 2026-01-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_type',
            field=models.CharField(choices=[('used_cm', 'Used Car & Motorcycle'), ('new_cm', 'New Car & Motorcycle'), ('direct_bs', 'Direct Buyer - Seller'), ('coe_car', 'COE Car')], default='used_cm', max_length=50),
        ),
    ]
