# Generated by Django 5.2.8 on 2025-12-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0006_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='message',
        ),
    ]
