# Generated by Django 5.2.8 on 2026-01-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0007_enquiry_enquiry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefinanceEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('vehicle_reg', models.CharField(max_length=20)),
                ('lta_access_code', models.CharField(max_length=50)),
                ('current_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('current_monthly_instalment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('privacy_policy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
