# Generated by Django 4.2 on 2025-12-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0007_remove_enquiry_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusetting',
            name='show_resources',
        ),
        migrations.AddField(
            model_name='menusetting',
            name='show_guides',
            field=models.BooleanField(default=True, verbose_name='Show Guides'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='coe_car',
            field=models.BooleanField(default=True, verbose_name='Car COE'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='coe_moto',
            field=models.BooleanField(default=True, verbose_name='Motorcycle COE'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='finance_coe_car',
            field=models.BooleanField(default=True, verbose_name='COE Cars'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='finance_direct',
            field=models.BooleanField(default=True, verbose_name='Direct Financing'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='finance_inhouse',
            field=models.BooleanField(default=True, verbose_name='In-House Financing'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='finance_new',
            field=models.BooleanField(default=True, verbose_name='New Cars'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='finance_phv',
            field=models.BooleanField(default=True, verbose_name='PHV Financing'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='finance_refinance',
            field=models.BooleanField(default=True, verbose_name='Refinance'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='finance_used',
            field=models.BooleanField(default=True, verbose_name='Used Cars'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='insurance_car',
            field=models.BooleanField(default=True, verbose_name='Car Insurance'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='insurance_motor',
            field=models.BooleanField(default=True, verbose_name='Motorcycle Insurance'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='show_about',
            field=models.BooleanField(default=True, verbose_name='Show About'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='show_coe',
            field=models.BooleanField(default=True, verbose_name='Show COE'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='show_contact',
            field=models.BooleanField(default=True, verbose_name='Show Contact'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='show_financing',
            field=models.BooleanField(default=True, verbose_name='Show Financing'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='show_home',
            field=models.BooleanField(default=True, verbose_name='Show Home'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='show_insurance',
            field=models.BooleanField(default=True, verbose_name='Show Insurance'),
        ),
        migrations.AlterField(
            model_name='menusetting',
            name='show_offers',
            field=models.BooleanField(default=True, verbose_name='Show Offers'),
        ),
    ]
