# Generated by Django 4.2 on 2026-01-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0008_refinanceenquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefinanceEnquiry',
        ),
        migrations.AddField(
            model_name='loanrate',
            name='int_rate_other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Other Companys Interest Rate'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='loan_type',
            field=models.CharField(choices=[('used_car', 'Used Car Loan'), ('new_car', 'New Car Loan'), ('direct_buyer', 'Direct Buyer → Seller Loan'), ('coe_car', 'COE Car Loan'), ('coe_ref', 'COE Refinancing Loan'), ('in_house', 'In-House Financing Loan'), ('phv_car', 'PHV Car Loan')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='enquiry_type',
            field=models.CharField(choices=[('Car Loan', 'Car Loan'), ('Motorcycle Loan', 'Motorcycle Loan'), ('COE Renewal', 'COE Renewal'), ('Insurance', 'Insurance'), ('Payment', 'Payment'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_type',
            field=models.CharField(choices=[('used_cm', 'Used Car & Motorcycle'), ('new_cm', 'New Car & Motorcycle'), ('direct_bs', 'Direct Buyer - Seller'), ('coe_car', 'COE Car'), ('coe_ref', 'COE Refinancing Loan'), ('in_house', 'In-House Financing Loan'), ('phv_car', 'PHV Car Loan'), ('renew_car', 'COE Renewal Car'), ('renew_motor', 'COE Renewal Motorcycle'), ('ins_car', 'Car Insurance'), ('ins_motor', 'Motorcycle Insurance')], default='used_cm', max_length=50),
        ),
    ]
