# Generated by Django 4.2 on 2025-12-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0008_remove_menusetting_show_resources_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menusetting',
            name='show_offers',
        ),
        migrations.AddField(
            model_name='menusetting',
            name='guides_calc',
            field=models.BooleanField(default=True, verbose_name='Calculator'),
        ),
        migrations.AddField(
            model_name='menusetting',
            name='guides_faq',
            field=models.BooleanField(default=True, verbose_name='FAQ'),
        ),
        migrations.AddField(
            model_name='menusetting',
            name='guides_install',
            field=models.BooleanField(default=True, verbose_name='Installment'),
        ),
        migrations.AddField(
            model_name='menusetting',
            name='guides_pay',
            field=models.BooleanField(default=True, verbose_name='Payment'),
        ),
        migrations.AddField(
            model_name='menusetting',
            name='show_rates',
            field=models.BooleanField(default=True, verbose_name='Show Rates'),
        ),
    ]
