# Generated by Django 4.2 on 2026-01-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0009_delete_refinanceenquiry_loanrate_int_rate_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersetting',
            name='telegram_url',
            field=models.URLField(blank=True, help_text='Please put your Telegram profile link here.'),
        ),
        migrations.AlterField(
            model_name='footersetting',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Please put your Facebook page link here.'),
        ),
        migrations.AlterField(
            model_name='footersetting',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Please put your Instagram profile link here.'),
        ),
        migrations.AlterField(
            model_name='footersetting',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='Please put your TikTok profile link here.'),
        ),
        migrations.AlterField(
            model_name='footersetting',
            name='whatsapp_url',
            field=models.URLField(blank=True, help_text='Please put your WhatsApp link here.'),
        ),
        migrations.AlterField(
            model_name='installmentsubmit',
            name='install_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='installmentsubmit',
            name='proof_pay',
            field=models.FileField(help_text='Please Download To View The Receipt.', upload_to='installments/'),
        ),
        migrations.AlterField(
            model_name='installmentsubmit',
            name='transfer_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanrate',
            name='int_rate_other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Other Company Interest Rate'),
        ),
        migrations.AlterField(
            model_name='loanrate',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='SGVehicleLoans Interest Rate'),
        ),
    ]
