# Generated by Django 4.2 on 2025-12-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0009_remove_menusetting_show_offers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('used_cm', 'Used Car & Motorcycle'), ('new_cm', 'New Car & Motorcycle'), ('direct_bs', 'Direct Buyer - Seller'), ('coe_car', 'COE Car')], max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='header_images/')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(choices=[('car', 'Car Insurance'), ('motorcycle', 'Motorcycle Insurance')], max_length=20, unique=True)),
                ('video', models.FileField(upload_to='header_videos/')),
            ],
        ),
    ]
