# Generated by Django 4.2 on 2025-12-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0010_headerimage_headervideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotoQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Yamaha', 'Yamaha'), ('Honda', 'Honda'), ('Suzuki', 'Suzuki'), ('Kawasaki', 'Kawasaki'), ('KTM', 'KTM'), ('Ducati', 'Ducati'), ('Royal Enfield', 'Royal Enfield'), ('BMW', 'BMW Motorrad'), ('Triumph', 'Triumph'), ('CFMOTO', 'CFMOTO'), ('SYM', 'SYM'), ('Kymco', 'Kymco'), ('Aprilia', 'Aprilia'), ('Benelli', 'Benelli'), ('Moto Guzzi', 'Moto Guzzi'), ('Bimota', 'Bimota'), ('Husqvarna', 'Husqvarna'), ('GasGas', 'GasGas'), ('Indian', 'Indian Motorcycle'), ('Harley-Davidson', 'Harley-Davidson'), ('Zero', 'Zero Motorcycles')], max_length=100)),
                ('model', models.CharField(max_length=255)),
                ('year_reg', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorce', 'Divorce')], max_length=10)),
                ('number', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('occupation', models.CharField(choices=[('Manager', 'Manager'), ('Engineer', 'Engineer'), ('Driver', 'Driver'), ('Technician', 'Technician'), ('Teacher', 'Teacher'), ('Nurse', 'Nurse'), ('Doctor', 'Doctor'), ('Accountant', 'Accountant'), ('Administrator', 'Administrator'), ('Salesperson', 'Salesperson'), ('Customer Service', 'Customer Service'), ('Supervisor', 'Supervisor'), ('Chef', 'Chef'), ('Cashier', 'Cashier'), ('Security Officer', 'Security Officer'), ('Cleaner', 'Cleaner'), ('Construction Worker', 'Construction Worker'), ('IT Specialist', 'IT Specialist'), ('Software Developer', 'Software Developer'), ('Designer', 'Designer'), ('Marketing Executive', 'Marketing Executive'), ('Human Resource', 'Human Resource'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Mechanic', 'Mechanic'), ('Logistics Coordinator', 'Logistics Coordinator'), ('Warehouse Assistant', 'Warehouse Assistant'), ('Delivery Rider', 'Delivery Rider'), ('Waiter', 'Waiter'), ('Barista', 'Barista'), ('Business Owner', 'Business Owner'), ('Self-Employed', 'Self-Employed'), ('Unemployed', 'Unemployed'), ('Student', 'Student'), ('Housewife', 'Housewife'), ('Retiree', 'Retiree'), ('Others', 'Others')], max_length=100)),
                ('ride_exp', models.CharField(choices=[('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('5+ Years', '5+ Years')], max_length=50)),
                ('ncd_disc', models.CharField(choices=[('0%', '0%'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%')], max_length=10)),
                ('licence', models.CharField(choices=[('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('5+ Years', '5+ Years')], max_length=50)),
                ('named_rider', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10)),
                ('claims', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4+', '4+')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('privacy_policy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
