# Generated by Django 4.2 on 2026-01-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0010_footersetting_telegram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
