# Generated by Django 4.2 on 2025-12-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0011_motoquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Honda', 'Honda'), ('BMW', 'BMW'), ('Toyota', 'Toyota'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Audi', 'Audi'), ('Volkswagen', 'Volkswagen'), ('Nissan', 'Nissan'), ('Mazda', 'Mazda'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Subaru', 'Subaru'), ('Volvo', 'Volvo'), ('Mitsubishi', 'Mitsubishi'), ('Ford', 'Ford'), ('Lexus', 'Lexus'), ('Porsche', 'Porsche'), ('Jaguar', 'Jaguar'), ('Land Rover', 'Land Rover'), ('Chevrolet', 'Chevrolet'), ('Peugeot', 'Peugeot'), ('Renault', 'Renault'), ('Ferrari', 'Ferrari'), ('Lamborghini', 'Lamborghini'), ('Maserati', 'Maserati'), ('Bentley', 'Bentley'), ('Rolls-Royce', 'Rolls-Royce'), ('McLaren', 'McLaren'), ('Bugatti', 'Bugatti'), ('Tesla', 'Tesla'), ('Infiniti', 'Infiniti'), ('Acura', 'Acura'), ('Mini', 'Mini'), ('Suzuki', 'Suzuki'), ('Isuzu', 'Isuzu'), ('Citroen', 'Citroen'), ('Alfa Romeo', 'Alfa Romeo'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Chrysler', 'Chrysler'), ('Daihatsu', 'Daihatsu')], max_length=100)),
                ('model', models.CharField(max_length=255)),
                ('year_reg', models.CharField(max_length=20)),
                ('usage', models.CharField(choices=[('Private and social', 'Private and social'), ('Private Hire, Ride hailing, Hitch', 'Private Hire, Ride hailing, Hitch'), ('Rental for self-drive', 'Rental for self-drive')], max_length=50)),
                ('scheme', models.CharField(choices=[('Off-peak', 'Off-peak'), ('Non off-peak', 'Non off-peak')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorce', 'Divorce')], max_length=10)),
                ('number', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('occupation', models.CharField(choices=[('Manager', 'Manager'), ('Engineer', 'Engineer'), ('Driver', 'Driver'), ('Technician', 'Technician'), ('Teacher', 'Teacher'), ('Nurse', 'Nurse'), ('Doctor', 'Doctor'), ('Accountant', 'Accountant'), ('Administrator', 'Administrator'), ('Salesperson', 'Salesperson'), ('Customer Service', 'Customer Service'), ('Supervisor', 'Supervisor'), ('Chef', 'Chef'), ('Cashier', 'Cashier'), ('Security Officer', 'Security Officer'), ('Cleaner', 'Cleaner'), ('Construction Worker', 'Construction Worker'), ('IT Specialist', 'IT Specialist'), ('Software Developer', 'Software Developer'), ('Designer', 'Designer'), ('Marketing Executive', 'Marketing Executive'), ('Human Resource', 'Human Resource'), ('Electrician', 'Electrician'), ('Plumber', 'Plumber'), ('Mechanic', 'Mechanic'), ('Logistics Coordinator', 'Logistics Coordinator'), ('Warehouse Assistant', 'Warehouse Assistant'), ('Delivery Rider', 'Delivery Rider'), ('Waiter', 'Waiter'), ('Barista', 'Barista'), ('Business Owner', 'Business Owner'), ('Self-Employed', 'Self-Employed'), ('Unemployed', 'Unemployed'), ('Student', 'Student'), ('Housewife', 'Housewife'), ('Retiree', 'Retiree'), ('Others', 'Others')], max_length=100)),
                ('vec_number', models.CharField(max_length=50)),
                ('ncd_disc', models.CharField(choices=[('0%', '0%'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%')], max_length=10)),
                ('licence', models.CharField(choices=[('1 Year', '1 Year'), ('2 Years', '2 Years'), ('3 Years', '3 Years'), ('4 Years', '4 Years'), ('5+ Years', '5+ Years')], max_length=50)),
                ('driver', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('claims', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4+', '4+')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('privacy_policy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='motoquote',
            name='named_rider',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=10),
        ),
    ]
