# Generated by Django 4.2 on 2025-12-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0012_carquote_alter_motoquote_named_rider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carquote',
            name='usage',
        ),
    ]
