# Generated by Django 4.2 on 2025-12-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0013_remove_carquote_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='COECarEnquiry',
            fields=[
            ],
            options={
                'verbose_name': 'COE Car Renewal Enquiry',
                'verbose_name_plural': 'COE Car Renewal Enquiries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apploan.enquiry',),
        ),
        migrations.CreateModel(
            name='COEMotorcycleEnquiry',
            fields=[
            ],
            options={
                'verbose_name': 'COE Motorcycle Renewal Enquiry',
                'verbose_name_plural': 'COE Motorcycle Renewal Enquiries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apploan.enquiry',),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='coe_category_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='coe_renewal_period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='is_phv',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='loan_type',
            field=models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle')], default='car', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
