# Generated by Django 4.2 on 2025-12-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0014_coecarenquiry_coemotorcycleenquiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryRenew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle')], max_length=20)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('coe_category_type', models.CharField(blank=True, max_length=255, null=True)),
                ('coe_renewal_period', models.CharField(blank=True, max_length=255, null=True)),
                ('is_phv', models.BooleanField(blank=True, null=True)),
                ('privacy_policy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='COECarEnquiry',
        ),
        migrations.DeleteModel(
            name='COEMotorcycleEnquiry',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='coe_category_type',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='coe_renewal_period',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='is_phv',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='loan_type',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='COERenewCar',
            fields=[
            ],
            options={
                'verbose_name': 'COE Car Renewal Enquiry',
                'verbose_name_plural': 'COE Car Renewal Enquiries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apploan.enquiryrenew',),
        ),
        migrations.CreateModel(
            name='COERenewMotorcycle',
            fields=[
            ],
            options={
                'verbose_name': 'COE Motorcycle Renewal Enquiry',
                'verbose_name_plural': 'COE Motorcycle Renewal Enquiries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apploan.enquiryrenew',),
        ),
    ]
