# Generated by Django 4.2 on 2025-12-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0015_enquiryrenew_delete_coecarenquiry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnquiryRenew',
        ),
        migrations.DeleteModel(
            name='COERenewCar',
        ),
        migrations.DeleteModel(
            name='COERenewMotorcycle',
        ),
    ]
