# Generated by Django 4.2 on 2025-12-10 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0016_delete_enquiryrenew_delete_coerenewcar_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarQuote',
            new_name='QuoteCar',
        ),
        migrations.RenameModel(
            old_name='MotoQuote',
            new_name='QuoteMotor',
        ),
    ]
