# Generated by Django 4.2 on 2025-12-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0018_enquiryrenew_coerenewcar_coerenewmotorcycle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnquiryRenew',
        ),
        migrations.DeleteModel(
            name='COERenewCar',
        ),
        migrations.DeleteModel(
            name='COERenewMotorcycle',
        ),
    ]
