# Generated by Django 4.2 on 2025-12-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0020_enquiryrenew_coerenewcar_coerenewmotorcycle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='COERenewCar',
        ),
        migrations.DeleteModel(
            name='COERenewMotorcycle',
        ),
        migrations.AlterField(
            model_name='enquiryrenew',
            name='is_phv',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True),
        ),
    ]
