# Generated by Django 4.2 on 2025-12-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0021_delete_coerenewcar_delete_coerenewmotorcycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryrenew',
            name='coe_category_type',
            field=models.CharField(blank=True, choices=[('Category A', 'Category A (Cars up To 1,600cc)'), ('Category B', 'Category B (Cars Above 1,600cc)'), ('Category C', 'Category C (Goods Vehicles & Buses)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enquiryrenew',
            name='coe_renewal_period',
            field=models.CharField(choices=[('5-Year Renewal', '5-Year Renewal'), ('10-Year Renewal', '10-Year Renewal')], default='car', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiryrenew',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiryrenew',
            name='is_phv',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enquiryrenew',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
