# Generated by Django 4.2 on 2025-12-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0022_alter_enquiryrenew_coe_category_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarEnquiry',
            fields=[
            ],
            options={
                'verbose_name': 'Car Enquiry',
                'verbose_name_plural': 'Car Enquiries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apploan.enquiryrenew',),
        ),
        migrations.CreateModel(
            name='MotorcycleEnquiry',
            fields=[
            ],
            options={
                'verbose_name': 'Motorcycle Enquiry',
                'verbose_name_plural': 'Motorcycle Enquiries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apploan.enquiryrenew',),
        ),
        migrations.AlterField(
            model_name='enquiryrenew',
            name='is_phv',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
    ]
