# Generated by Django 4.2 on 2025-12-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0023_carenquiry_motorcycleenquiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('car_source', models.CharField(choices=[('direct_owner', 'Direct Owner'), ('car_dealer', 'Car Dealer')], max_length=50)),
                ('vehicle_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('omv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arf', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registration_date', models.DateField()),
                ('registration_number', models.CharField(max_length=50)),
                ('lta_access_code', models.CharField(max_length=50)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_tenure', models.PositiveIntegerField()),
                ('loan_type', models.CharField(choices=[('used_car', 'Used Car Loan'), ('new_car', 'New Car Loan'), ('coe_car', 'COE Car Loan'), ('direct_buyer', 'Direct Buyer → Seller Loan')], max_length=50)),
                ('repayment_mode', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('preferred_bank', models.CharField(choices=[('maybank', 'Maybank'), ('uob', 'UOB'), ('dbs', 'DBS/POSB'), ('ocbc', 'OCBC'), ('hlf', 'Hong Leong Finance'), ('others', 'Others')], max_length=50)),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remarks', models.TextField()),
                ('privacy_policy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='carenquiry',
            options={'verbose_name': 'Enquiry COE Renew Car', 'verbose_name_plural': 'Enquiries COE Renew Car'},
        ),
        migrations.AlterModelOptions(
            name='motorcycleenquiry',
            options={'verbose_name': 'Enquiry COE Renew Motorcycle', 'verbose_name_plural': 'Enquiries COE Renew Motorcycle'},
        ),
    ]
