# Generated by Django 4.2 on 2025-12-16 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0024_apply_alter_carenquiry_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
