# Generated by Django 4.2 on 2025-12-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0025_delete_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyCOE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motor', 'Motorcycle')], max_length=10)),
                ('full_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('consent', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarCOE',
            fields=[
            ],
            options={
                'verbose_name': 'Car COE Application',
                'verbose_name_plural': 'Car COE Applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apploan.applycoe',),
        ),
        migrations.CreateModel(
            name='MotorCOE',
            fields=[
            ],
            options={
                'verbose_name': 'Motorcycle COE Application',
                'verbose_name_plural': 'Motorcycle COE Applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apploan.applycoe',),
        ),
    ]
