# Generated by Django 4.2 on 2025-12-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apploan', '0026_applycoe_carcoe_motorcoe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
            ],
            options={
                'verbose_name': 'General Applications',
                'verbose_name_plural': 'General Applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apploan.apply',),
        ),
        migrations.CreateModel(
            name='Enquiries',
            fields=[
            ],
            options={
                'verbose_name': 'General Enquiries',
                'verbose_name_plural': 'General Enquiries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apploan.enquiry',),
        ),
        migrations.AlterModelOptions(
            name='carcoe',
            options={'verbose_name': 'Application COE Renewal Car', 'verbose_name_plural': 'Application COE Renewal Car'},
        ),
        migrations.AlterModelOptions(
            name='motorcoe',
            options={'verbose_name': 'Application COE Renewal Motorcycle', 'verbose_name_plural': 'Application COE Renewal Motorcycle'},
        ),
    ]
